# Generated by Django 2.1 on 2018-08-31 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Revista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(max_length=25, unique=True)),
                ('titulo', models.TextField(max_length=100)),
                ('pagina', models.IntegerField()),
                ('publicacao', models.DateField()),
                ('qtde', models.IntegerField()),
            ],
        ),
    ]
